on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

name: FFmpeg

jobs:
  build:
    name: compile apple and android ffmpeg then deploy
    runs-on: macos-14
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
        local-cache: true
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install denpendencies
      run: |
        brew install lame
        echo "✅ lame installed at path $(which lame)"
        ./main.sh install -l 'openssl opus' -p ios     
    - name: One Step
      run: .github/workflows/onestep.sh ffmpeg ios